### ISSUE TITLE
Implement Game logic subsystem

### ISSUE THREAD

**Issue by e-harvey** [e-harvey/ShapesApp#3]
- Add deoxygen style comments to all methods.
- Continue testing with emulator and personal android devices

**Comment by e-harvey** [comment]
We are getting the same error posted in the link below.  It has to do with the bitmap rendering.  The error occurs after suspending the application, returning to the application, and going to settings->main menu or settings->logout.

http://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio

@benjlouie

**Comment by benjlouie** [comment]
I couldn't replicate the error, not on my phone or the emulator.
I did find another bug though. If you go into the game then logout, you can press back and go back to the settings screen and the rest of the game

**Comment by e-harvey** [comment]
Yeah, I think you fixed this yesterday -- after I merged in your changes this bug went away.  Ok, I'll try to fix that.  I'm about to push and I think the tutorial video is working but it doesn't display on the emulator.  Please check with your device after I push.

**Comment by benjlouie** [comment]
The video player does come up if you tap the center of the help screen. The player appears to be loading/playing, but nothing is displayed.
You can still press back after logging out to go to the settings screen. The only difference is you get kicked out if you try to go into the settings screen from the main menu afterward.

**Comment by e-harvey** [comment]
Ok, I'll see if I can fix the media player.  I actually fixed the other bug from logging out now.

**Comment by e-harvey** [comment]
Ok, fixed help screen will push in a sec.  On your physical device, if you quit the app without logging out and then start the app up again do you have to login or does it take your straight to the main menu?

**Comment by e-harvey** [comment]
Nvm that's fixed. Pushing.

**Comment by benjlouie** [comment]
It makes you log in again. I'll check out what you commit tomorrow

**Comment by e-harvey** [comment]
It's fixed.
